export const setPlayList = 'setPlayList' // 播放列表 接收数组
export const setCurrentSong = 'setCurrentSong' // 设置正在播放的歌曲
export const setPlay = 'setPlay' // 播放状态
export const getcurrentTime = 'getcurrentTime' // 获取播放当前进度
export const getmaxTime = 'getmaxTime' // 总进度
export const setFile = 'setFile' // 提供下在的资源
export const setArtists = 'setArtists' // 歌曲详情
export const setMusicToken = 'setMusicToken' // 设置token
export const setUserInfo = 'setUserInfo'
